export const signupText = {
  heading: 'Create an account',
  subtext: 'Already have an account?',
  loginLinkText: 'Log in',
  nameLabel: 'Name',
  namePlaceholder: 'Your name',
  emailLabel: 'Email',
  emailPlaceholder: 'you@example.com',
  passwordLabel: 'Password',
  passwordPlaceholder: '••••••••',
  confirmPasswordLabel: 'Confirm Password',
  confirmPasswordPlaceholder: '••••••••',
  secretKeyLabel: 'Admin Secret Key (optional)',
  secretKeyPlaceholder: 'Enter secret key if you have',
  buttonText: 'Sign up',
  buttonLoadingText: 'Signing up...',
  errorPasswordMismatch: 'Passwords do not match',
  errorDefault: 'Signup failed. Please try again.',
  successMessage: 'Signup successful! Redirecting to login...',
};
